baseURL = "https://39hz.github.io/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "Whisper in 39Hz"
theme = "PaperMod"

[params]
  env = "production"
  description = "Soft Thoughts. Deep Signals. 在喧嚣之外，听见轻语。"
  author = "39Hz"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowPostNavLinks = true
  defaultTheme = "auto"
  disableThemeToggle = false
  DateFormat = "2006-01-02"
  UseHugoToc = true

  [params.homeInfoParams]
    Title = "Whisper in 39Hz"
    Content = "Soft Thoughts. Deep Signals.\n在喧嚣之外，听见轻语。"

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "projects"
  name = "项目"
  url = "/projects/"
  weight = 30

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 40

[services]
  [services.googleAnalytics]
    id = "G-10HT2BHMV3"